name: Typecheck

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node 16.13.0
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.13.0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.11
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Typecheck
        run: yarn typecheck
